// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register', async function() {
    await driver.get("http://localhost:4200/");
    await driver.manage().window().setRect({ width: 736, height: 824 });
    await driver.findElement(By.css(".table-btn")).click();
    await driver.findElement(By.css("a")).click();

    // Attente explicite pour s'assurer que l'élément 'username' est visible avant de cliquer
    await driver.wait(until.elementLocated(By.name("username")), 10000);  // Attendre jusqu'à 10 secondes
    await driver.findElement(By.name("username")).click();
    await driver.findElement(By.name("username")).sendKeys("alouich");

    // Répétez cette logique pour les autres champs
    await driver.findElement(By.name("email")).click();
    await driver.findElement(By.name("email")).sendKeys("chgmail.com");
    await driver.findElement(By.name("password")).click();
    await driver.findElement(By.name("password")).sendKeys("chaima123");
    await driver.findElement(By.css(".btn")).click();
    await driver.findElement(By.name("username")).click();
    await driver.findElement(By.name("username")).sendKeys("alouichaima");
    await driver.findElement(By.css(".btn")).click();

  })
})
