// // Generated by Selenium IDE
// const { Builder, By, Key, until } = require('selenium-webdriver')
// const assert = require('assert')

// describe('update_category', function() {
//   this.timeout(30000)
//   let driver
//   let vars
//   beforeEach(async function() {
//     driver = await new Builder().forBrowser('chrome').build()
//     vars = {}
//   })
//   afterEach(async function() {
//     await driver.quit();
//   })
//   it('update_category', async function() {
//     // Test name: update_category
//     // Step # | name | target | value
//     // 1 | open | http://localhost:4200/admin/categories |
//     await driver.get("http://localhost:4200/admin/categories")
//     // 2 | setWindowSize | 1552x840 |
//     await driver.manage().window().setRect({ width: 1552, height: 840 })
//     // 3 | click | css=tr:nth-child(1) button:nth-child(1) |
//     await driver.findElement(By.css("tr:nth-child(1) button:nth-child(1)")).click()
//     // 4 | click | id=description |
//     await driver.findElement(By.id("description")).click()
//     // 5 | type | id=description | pizza neptune
//     await driver.findElement(By.id("description")).sendKeys("pizza neptune")
//     // 6 | click | css=.btn |
//     await driver.findElement(By.css(".btn")).click()
//   })
// })
